### ISSUE TITLE
[Help][BOJ, 8958] OX퀴즈

### ISSUE THREAD

**Issue by soheeoott** [shirohoo/Practice-Algorithm#273]
## 문제
https://www.acmicpc.net/problem/8958
​
## 작성한 코드
```java
import java.io.*;

public class Main {
    public static void main(String[] args) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        int tCase = Integer.parseInt(br.readLine());
        String ox[] = new String[tCase];

        for(int i=0; i < tCase; i++){
            ox[i] = br.readLine();
        }
        br.close();

        for(int i=0; i<ox.length; i++) {
            int cnt = 0;
            int sum = 0;
            for(int j=0; j<ox[i].length(); j++){
                if(ox[i].charAt(j) == 'O'){
                    cnt++;
                } else {
                    cnt = 0;
                }
                sum += cnt;
            }
            System.out.print(sum + "\n");
        }
    }
}
```
​
## 코드 설명

> "OOXXOXXOOO"와 같은 OX퀴즈의 결과가 있다. 
O는 문제를 맞은 것이고, X는 문제를 틀린 것이다. 
"OOXXOXXOOO"의 점수는 1+2+0+0+1+0+0+1+2+3 = 10점이다.

문자열을 배열로 넣어서 O 가 있으면 카운트 변수의 값을 증가해주고, 
반복문을 돌다가 X 가 있다면 카운트 변수의 값을 0으로 초기화하여 
카운트 변수를 총 합 변수 sum 안에 넣은 코드입니다.

코드의 문제는 아니고, 특정 문자열을 기준으로 배열안 문자열을 분리하려면
indexOf, substring, split 등의 방법을 사용하는데,
특정 기준 없이 문자열을 하나씩 쪼개는 방법이 떠오르지 않아 이 부분은 참고를 하였습니다..
혹여 foreach 구문으로 될까 하였는데 그냥 통째로 출력되더라구요! 
다른 방법이 있을까요??

**Comment by shirohoo** [comment]
> 코드의 문제는 아니고, 특정 문자열을 기준으로 배열안 문자열을 분리하려면
indexOf, substring, split 등의 방법을 사용하는데,
특정 기준 없이 문자열을 하나씩 쪼개는 방법이 떠오르지 않아 이 부분은 참고를 하였습니다..
혹여 foreach 구문으로 될까 하였는데 그냥 통째로 출력되더라구요!

이 부분이 잘 이해가 안됩니다 😭

**Comment by soheeoott** [comment]
> > 코드의 문제는 아니고, 특정 문자열을 기준으로 배열안 문자열을 분리하려면
> > indexOf, substring, split 등의 방법을 사용하는데,
> > 특정 기준 없이 문자열을 하나씩 쪼개는 방법이 떠오르지 않아 이 부분은 참고를 하였습니다..
> > 혹여 foreach 구문으로 될까 하였는데 그냥 통째로 출력되더라구요!
> 
> 이 부분이 잘 이해가 안됩니다 😭

아! 이 부분은
보통 문자열을 분리할 때 특정 기준이 있다면 indexOf, subString, split 등으로 문자열을 분리하잖아요!
근데 이 경우에는 특정 기준은 없고 그냥 "OOXXOO" 형태의 문자를 하나씩 한개로 쪼개는?? 방법인데,
charAt 를 활용해서 풀이하는 방법을 검색해서 알게되었는데, 이 방법 외에는 없을까 하여 문의드렸습니다!

**Comment by shirohoo** [comment]
String은 char의 배열형인데요
charAt은 간단하게 배열의 인덱스를 생각하시면 됩니다.

예를들어
```
String s = "안녕하세요";
```
라는 문자열이 있다면 이는
```
char[] chars = {'안', '녕', '하', '세', '요'};
```
와 같다고 볼 수 있습니다.

```
chars[0] == '안';
chars[1] == '녕';
chars[2] == '하';
chars[3] == '세';
chars[4] == '요';
```

그렇다면 위와 같은 코드는,

```
s.charAt(0) == '안';
s.charAt(1) == '녕';
s.charAt(2) == '하';
s.charAt(3) == '세';
s.charAt(4) == '요';
```
와 본질적으로 다를 게 없습니다.
단지 더 가독성좋게, 편하게 사용하기 위해 String 클래스에서 추상화를 했을 뿐입니다.

실제로도 charAt 메소드의 구현 코드를 보면

```
public static char charAt(byte[] value, int index) {
        if (index < 0 || index >= value.length) {
            throw new StringIndexOutOfBoundsException(index);
        }
        return (char)(value[index] & 0xff);
    }
```

이와 같이 char 배열의 인덱스를 통해 문자를 꺼내오는 걸 확인 할 수 있습니다.
문자(char)를 문자열(String)에서 꺼내오는 방법은 배열에서 원소를 꺼내오는 것과 본질적으로 다를 게 없습니다.

결론적으로 제 생각에는 딱히 다른 방법은 없을 것 같고,
이런 상황 대신 문자를 특정 패턴으로 쪼개는 패턴 매칭 알고리즘으로 KMP나 Boyer-Moore 알고리즘 등이 있긴합니다.

더 좋은 의견이 있다면 저도 듣고 배우고 싶네요. 🤗

**Comment by soheeoott** [comment]
헉 예제까지 친절한 설명 감사드립니다!
혹여 다른 방법을 알게된다면 코멘트 남기겠습니다. 감사합니다!!
🙇‍♀️🙇‍♀️
